version: '3.8'

services:
  homepage:
    environment:
      # Variable de entorno que la app usará para conectarse a MongoDB
      - DATABASE_URI=mongodb://mongodb:testmongo@mongodb:27017/mydb?authSource=admin
    depends_on:
        - get
        - mongodb
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3030:3030"

  get:
    environment:
      # Variable de entorno que la app usará para conectarse a MongoDB
      - DATABASE_URI=mongodb://mongodb:testmongo@mongodb:27017/mydb?authSource=admin
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile.get
    ports:
      - "8081:3030"

  post:
    environment:
      # Variable de entorno que la app usará para conectarse a MongoDB
      - DATABASE_URI=mongodb://mongodb:testmongo@mongodb:27017/mydb?authSource=admin
    depends_on:
        - get
        - mongodb
    build:
      context: .
      dockerfile: Dockerfile.post
    ports:
      - "8082:3030"

  put:
    environment:
      # Variable de entorno que la app usará para conectarse a MongoDB
      - DATABASE_URI=mongodb://mongodb:testmongo@mongodb:27017/mydb?authSource=admin
    depends_on:
        - get
        - mongodb
    build:
      context: .
      dockerfile: Dockerfile.put
    ports:
      - "8083:3030"

  delete:
    environment:
      # Variable de entorno que la app usará para conectarse a MongoDB
      - DATABASE_URI=mongodb://mongodb:testmongo@mongodb:27017/mydb?authSource=admin
    depends_on:
        - get
        - mongodb
    build:
      context: .
      dockerfile: Dockerfile.delete
    ports:
      - "8084:3030"
  
  # Servicio de base de datos MongoDB
  mongodb:
    image: mongo:6  # Usa la imagen oficial de MongoDB versión 6
    container_name: mongodb  # Nombre fijo para el contenedor
    ports:
      - "27018:27017"  # Expone el puerto interno 27017 como 27018 en el host
    environment:
      # Crea el usuario administrador de MongoDB
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: testmongo
    volumes:
      - mongo_data:/data/db  # Usa un volumen persistente para los datos de Mongo

# Volúmenes para mantener datos persistentes incluso si se elimina el contenedor
volumes:
  mongo_data:
