version: '3.8'

services:
  homepage:
    environment:
      - DATABASE_URI=mongodb://mongodb:testmongo@mongodb:27017/mydb?authSource=admin
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile.frontend
    expose:
      - "3030"

  get:
    environment:
      - DATABASE_URI=mongodb://mongodb:testmongo@mongodb:27017/mydb?authSource=admin
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile.get
    expose:
      - "3030"

  post:
    environment:
      - DATABASE_URI=mongodb://mongodb:testmongo@mongodb:27017/mydb?authSource=admin
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile.post
    expose:
      - "3030"

  put:
    environment:
      - DATABASE_URI=mongodb://mongodb:testmongo@mongodb:27017/mydb?authSource=admin
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile.put
    expose:
      - "3030"

  delete:
    environment:
      - DATABASE_URI=mongodb://mongodb:testmongo@mongodb:27017/mydb?authSource=admin
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile.delete
    expose:
      - "3030"

  nginx:
    image: nginx:latest
    depends_on:
      - homepage
      - get
      - post
      - put
      - delete
    ports:
      - "8080:3030"   # Aquí expone el puerto 3030 del contenedor NGINX al 8080 del host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: testmongo
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
