# Versión del esquema de Docker Compose
version: '3.8'

services:
  # Servicio principal: aplicación Go
  app:
    image: fhernandez004/cloudex2:latest  # Imagen publicada en Docker Hub
    ports:
      - "3030:3030"  # Expone el puerto 3030 del contenedor en el puerto 3030 del host
    depends_on:
      - mongodb  # Indica que 'app' debe arrancar después del servicio 'mongodb'
    environment:
      # Variable de entorno que la app usará para conectarse a MongoDB
      - DATABASE_URI=mongodb://mongodb:testmongo@mongodb:27017/mydb?authSource=admin
    restart: unless-stopped  # Reinicia automáticamente si falla, a menos se haga manualmente

  # Servicio de base de datos MongoDB
  mongodb:
    image: mongo:6  # Usa la imagen oficial de MongoDB versión 6
    container_name: mongodb  # Nombre fijo para el contenedor
    ports:
      - "27018:27017"  # Expone el puerto interno 27017 como 27018 en el host
    environment:
      # Crea el usuario administrador de MongoDB
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: testmongo
    volumes:
      - mongo_data:/data/db  # Usa un volumen persistente para los datos de Mongo

# Volúmenes para mantener datos persistentes incluso si se elimina el contenedor
volumes:
  mongo_data:
